---
- hosts: demo

  tasks:
  - name: ping
    ping:

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
    become: true

  - name: install nginx
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - nginx
    become: true